### ISSUE TITLE
fails to build on Ubuntu 16

### ISSUE THREAD

**Issue by lucasduffey** [JiaoXianjun/LTE-Cell-Scanner#11]
something to do with the library search path not finding RTLSDR and ITPP

I created two pull requests to fix it
FindRTLSDR.cmake - https://github.com/JiaoXianjun/LTE-Cell-Scanner/pull/10
FindITPP.cmake - https://github.com/JiaoXianjun/LTE-Cell-Scanner/pull/9
FindBLADERF.cmake - https://github.com/JiaoXianjun/LTE-Cell-Scanner/pull/12

**Comment by alohau** [comment]
if you install x64 os the path may be:
/usr/lib/x86_64-linux-gnu
you shoule modify FindRTLSDR.cmake& FindITPP.cmake
[https://github.com/Evrytania/LTE-Cell-Scanner/issues/15](url)

**Comment by lucasduffey** [comment]
yes I made pull requests to solve those issues - which are in my first comment
