### ISSUE TITLE
I see nothing with HackRF

### ISSUE THREAD

**Issue by Pyr3x** [JiaoXianjun/LTE-Cell-Scanner#13]
Compiled after multiple changes but I can't see any LTE cells... Why? Using a HackRF

**Comment by jackpudding** [comment]
Me Also.

I can see very strong LTE:
![image](https://user-images.githubusercontent.com/37270557/37255511-e4fbaf06-2523-11e8-967a-0c0e5fcbc03c.png)

But i run across whole 10MHz and no detect from LTECELLSCANNER.. Is look for TDD not FDD signals?

**Comment by tomasdev** [comment]
Similar situation. In NYC, I know T-Mobile is on 1800-2100 MHz and yet it doesn't see it.

**Comment by JiaoXianjun** [comment]
please take a look at: https://github.com/JiaoXianjun/LTE-Cell-Scanner/issues/41
