### ISSUE TITLE
hackrf on ubuntu14.03

### ISSUE THREAD

**Issue by Mitchell1314** [JiaoXianjun/LTE-Cell-Scanner#15]
Hi sir,
    I have installed LTE-Cell-Scanner on my ubuntu14.03. When I run "CellSearch --freq-start 1890000000" with hackrf,I got an error:
![image](https://cloud.githubusercontent.com/assets/15179223/23247040/a9e639ea-f9d2-11e6-8bac-4798f4653a0b.png)
 How can I fix it? Waiting for your reply. Thank you!

**Comment by suduma** [comment]
+1 for newer versions not being compatible, I noticed during compile it did not find the libraries it may be a simple fix but If I get tired of trying to get it to compile with the newer hackrf ill try a hackrf revision around 2014 April 1st next.

Source https://devhub.io/repos/JiaoXianjun-LTE-Cell-Scanner
