### ISSUE TITLE
Open file failed

### ISSUE THREAD

**Issue by amrabbas** [JiaoXianjun/LTE-Cell-Scanner#2]
Hello,

I get this error:
setup_filter_my: open file failed! Please make sure program can find filter_my_kernels.cl

I am not sure if I understand what is meant by ".cl files in LTE-Cell-Scanner/src have been copy to program directory". What is meant by "program directory"?

I tried adding the /LTE-Cell-Scanner/src directory to the $PATH variable. I also tried adding the /LTE-Cell-Scanner/src directory to /etc/environment

Thanks for the help

**Comment by Omar-D** [comment]
@JiaoXianjun Thanks for this solution teacher and my dear brother, i appreciate that so i have a little idea.

What about making a little edit in the project, i mean exactly in make files to make the project copy *.cl files when compile or when use `make` and `make install` commands exactly.

Thanks in advance!
