### ISSUE TITLE
HackRF testing problem on Ubuntu 16.04

### ISSUE THREAD

**Issue by jjbaek35** [JiaoXianjun/LTE-Cell-Scanner#24]
I tested open-source baed LTE-Cell-Scanner with HackRF one (https://github.com/JiaoXianjun/LTE-Cell-Scanner). I installed HackRF host and LTE-Cell-Scanner successfully
When I run the LTE-Cell-Scanner, it found device but not scan.
It should start searching the frequency turn by turn,  but it doesn't pass to next frequency.
(just 1 step)

$ CellSearch -s 939e6 -e 940e6
LTE CellSearch (release) beginning. 1.0 to 1.1.0: OpenCL/TDD/HACKRF/bladeRF/ext-LNB added by Jiao Xianjun(putaoshu@gmail.com)
PPM: 0
correction: 1
HACKRF device FOUND!
Use HW begin with 939MHz actual 939MHz 1.92e+06MHz
Search frequency: 939 to 940 MHz
with freq correction: 0 kHz
Search PSS at fo: -60 to 55 kHz

Examining center frequency 939 MHz ... try 0

// and no response.

* my OS version information is Ubuntu 16.04

*hackrf_info version: git-abxxx68
libhackrf version: git-abxxx68 (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000a06063cxxxc8a5f
Board ID Number: 2 (HackRF One)
Firmware Version: 2018.01.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x00xxx5f

**Comment by jjbaek35** [comment]
I solved it by myself. I thought HackRF one is upgraded on firmware so it causes compatibility issues.
I handled the exceptional error procedures.

**Comment by b4cktr4ck2** [comment]
@jjbaek35 Could you please share what you did to handle the error procedures? I'm having similar issues.

**Comment by r00tb3** [comment]
> I solved it by myself. I thought HackRF one is upgraded on firmware so it causes compatibility issues.
> I handled the exceptional error procedures.

Can you pls explain how did you resolve the issue?

I'm facing the same problem.

Regards.

**Comment by jjbaek35** [comment]
Hi

I modified the part causing error manually.  I will share the files with
you by tomorrow.
You can try it.

Please wait for me.

Thank you

Best,

**Comment by jjbaek35** [comment]
Sorry for the late reply,

Please extract the attached file. and try to install it with README.md file

Good luck!

 LTE-privacy-master.zip
<https://drive.google.com/file/d/1NjsHji5RHQiXNBIJXekrIbXpGf550ic9/view?usp=drive_web>
