### ISSUE TITLE
cmake 

### ISSUE THREAD

**Issue by mozoho77** [JiaoXianjun/LTE-Cell-Scanner#29]
I have cmake problem when trying to compile. Why include_subdirectory is unknown command >

```

cmake version 3.7.2
```
```
CMake Error at CMakeLists.txt:1 (INCLUDE_SUBDIRECTORY):
  Unknown CMake command "INCLUDE_SUBDIRECTORY".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```
../CMakeLists.txt
```
CMAKE_MINIMUM_REQUIRED( VERSION 3.7 )
# allow more human readable "if then else" constructs
#SET( CMAKE_ALLOW_LOOSE_LOOP_CONSTRUCTS TRUE )
# Add the local Find*.cmake scripts
LIST (APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/Modules)

PROJECT( CellSearch )
ENABLE_TESTING()

```

**Comment by velichkov** [comment]
Hi @mozoho77,

> CMake Error at CMakeLists.txt:1 (INCLUDE_SUBDIRECTORY):
  Unknown CMake command "INCLUDE_SUBDIRECTORY".

This looks like https://github.com/jocover/OpenUSRP/issues/8

Have you done any modifications to CMakeLists.txt or any other file?
Could you provide list of all commands that you have executed (with all their arguments)?
If you are following some instructions (tutorial, blog post or something) provide a link to it.

Provide the full output of following commands executed in `LTE-Cell-Scanner` directory.
```
git describe --always
git status
grep INCLUDE_SUBDIRECTORY . -R
```
