### ISSUE TITLE
HACKRF LIB not found

### ISSUE THREAD

**Issue by TheOncomingStorm** [JiaoXianjun/LTE-Cell-Scanner#3]
I have

/usr/lib64/libhackrf.so
/usr/lib64/libhackrf.so.0
/usr/lib64/libhackrf.so.0.4.0

but when I run cmake I get:

```
-- Try to find OPENCL LIB
-- Found OpenCL LIB: /usr/lib64/libOpenCL.so
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   thread
--   system
-- Found ITPP: /usr/lib64/libitpp.so
-- Found FFTW: /usr/lib64/libfftw3.so
-- Try to find HACKRF LIB
-- HACKRF LIB not found
-- Configuring done
-- Generating done
-- Build files have been written to: ./src/LTE-Cell-Scanner/build
```

Any ideas why it might not detect the hackrf libraries when it clearly detects the others?
I'm using Gentoo if that helps any.

**Comment by lucasduffey** [comment]
I assume it's related to cmake/Modules/FindHACKRF.cmake - but I can't tell myself

**Comment by alohau** [comment]
if you are x64 OS 
add path:
/usr/lib/x86_64-linux-gnu

**Comment by TheOncomingStorm** [comment]
alohau, there is no such path for Gentoo.  I ended up fixing it anyway, though not sure how.
