### ISSUE TITLE
Understanding CELL ID value given by software

### ISSUE THREAD

**Issue by f4gkr** [JiaoXianjun/LTE-Cell-Scanner#30]
I am trying to match the detected cells with public LTE databases. A search from my home (I leave in the countryside, not many cells around) gives for example a cell : 
DPX CID A      fc   freq-offset RXPWR C nRB P  PR CrystalCorrectionFactor
FDD **276** 2    **796M**         -104h -13.5 N  50 N one 0.99999986932714024501

While www.cellmapper.net gives the following ID for that cell : 
Cell Identifier  **154653700**
Downlink Frequency **796** MHz

What is the relashionship between CELL ID displayed by CellSearch and values public databases ?
Sorry if the question is stupid
thanks

**Comment by JiaoXianjun** [comment]
It is a very good question.
I think the CID is the physical layer cell id, which is explained here: http://rfmw.em.keysight.com/wireless/helpfiles/89600B/WebHelp/Subsystems/lte/content/lte_dlg_fmt_cellid.htm

The cellmapper gives you enodeb-id, which is explained here: http://www.techtrained.com/the-ultimate-cheat-sheet-for-lte-identifiers/#:~:text=Enodeb%2Did,uniquely%20identifies%20an%20eNodeB%20globally.

**Comment by f4gkr** [comment]
Thanks for your reply !

Le mer. 10 mars 2021 à 20:44, Jiao Xianjun ***@***.***> a
écrit :
