### ISSUE TITLE
Does the Matlab Code still run? found your file on filexchange but can't make it work

### ISSUE THREAD

**Issue by popepay** [JiaoXianjun/LTE-Cell-Scanner#4]
Hello, I found your file on filexchange, rated at 5 stars by 2 reviewers and would like to try it.

unfortunately I can't find how to run the code. can you please help me?

CellSearch seems to be the main function, but it has like 10 inputs. if you could just give me an example, that's all I'll need! thanks

**Comment by JiaoXianjun** [comment]
Please find these in README:

0x02.3 LTE_DL_receiver (Matlab script. Decode RRC SIB message in PDSCH by reading captured signal bin file)

0x02.4 LTE_DL_receiver 1890 40 40 (Matlab script. Decode SIB at 1890MHz lively with LNA VGA gain of hackRF 40dB 40dB)

**Comment by JiaoXianjun** [comment]
I confirm the matlab script still run. You can find my restructured/clarified new readme.
