### ISSUE TITLE
Repository Size

### ISSUE THREAD

**Issue by danieldjewell** [JiaoXianjun/LTE-Cell-Scanner#40]
This repository has continued to grow over time. I just cloned it and it's over **1GB** (of git data!)! When checked out that makes it ~1.6GB!

Is it absolutely necessary to have the test data in the main repo? What about storing it separately and using a git submodule? It would be really nice to not have to download *so much* data.

**Comment by JiaoXianjun** [comment]
Good idea. I will try.

But are you sure this could reduce the size of initial clone? I though the git record "ALL HISTORY"?

**Comment by JiaoXianjun** [comment]
The test data only occupy about 500M, it is much smaller than 1.6GB.
Even I remove them, the repo size won't shrink, because they are still there in the history. Remember that git keep all history.

Only way is that remove some history...

**Comment by JiaoXianjun** [comment]
I tried all kinds of method on internet. Now the zip download is very small, but git clone is still ~ 1G

**Comment by JiaoXianjun** [comment]
Now it is very small even git clone. Files are in https://github.com/JiaoXianjun/LTE-Cell-Scanner-big-file
