### ISSUE TITLE
Not able to get any LTE cell

### ISSUE THREAD

**Issue by amitpathania** [JiaoXianjun/LTE-Cell-Scanner#41]
I am trying to search LTE cells using RTL-SDR but I am not able to get any results. 

`LTE CellSearch (release) beginning. 1.0 to 1.1.0: OpenCL/TDD/HACKRF/bladeRF/ext-LNB added by Jiao Xianjun(putaoshu@gmail.com)
  PPM: 0
  correction: 1
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
[R82XX] PLL not locked!
RTLSDR device FOUND!
capture_data Warning: It is not RTLSDR_TUNER_E4000
set fc_programmed=fc_requested
Use  HW  begin with 1.7MHz actual 1.7MHz 1.92e+06MHz
    Search frequency: 1.7 to 1.9 MHz
with freq correction: 0 kHz
    Search PSS at fo: -60 to 55 kHz

Examining center frequency 1.7 MHz ... try 0
capture_data Warning: It is not RTLSDR_TUNER_E4000
set fc_programmed=fc_requested
[R82XX] PLL not locked!
Allocating 15 zero-copy buffers

input level: avg abs(real) 0.00289919 avg abs(imag) 0.00288717
Hit        PAR [3.83983 3.90074]dB
PSS XCORR  cost 2.03533s

Examining center frequency 1.8 MHz ... try 0
capture_data Warning: It is not RTLSDR_TUNER_E4000
set fc_programmed=fc_requested
[R82XX] PLL not locked!
Allocating 15 zero-copy buffers

input level: avg abs(real) 0.00296552 avg abs(imag) 0.00297631
Hit        PAR [3.51866 3.70337]dB
PSS XCORR  cost 2.04538s

Examining center frequency 1.9 MHz ... try 0
capture_data Warning: It is not RTLSDR_TUNER_E4000
set fc_programmed=fc_requested
[R82XX] PLL not locked!
Allocating 15 zero-copy buffers

input level: avg abs(real) 0.00297955 avg abs(imag) 0.00297672
Hit        PAR [3.41131 3.96509]dB
PSS XCORR  cost 2.04292s
No LTE cells were found...
`

**Comment by JiaoXianjun** [comment]
Search frequency: 1.7 to 1.9 MHz ???
I think your command line has some mistakes? Can you paste your command here?

**Comment by amitpathania** [comment]
Sorry my mistake. But I changed frequency to 1805 Mhz band but still no results.

**Comment by JiaoXianjun** [comment]
Maybe 1805 is not a service downlink frequency of your local operator.

Don't know which LTE downlink frequency is in use in your region? Check by the engineering mode of your cell phone (please google) or this website https://www.spectrummonitoring.com/frequencies.php

**Comment by amitpathania** [comment]
LTE CellSearch (release) beginning. 1.0 to 1.1.0: OpenCL/TDD/HACKRF/bladeRF/ext-LNB added by Jiao Xianjun(putaoshu@gmail.com)
  PPM: 0
  correction: 1
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
RTLSDR device FOUND!
capture_data Warning: It is not RTLSDR_TUNER_E4000
set fc_programmed=fc_requested
Use  HW  begin with 875MHz actual 875MHz 1.92e+06MHz
    Search frequency: 875 to 875 MHz
with freq correction: 0 kHz
    Search PSS at fo: -140 to 135 kHz

Examining center frequency 875 MHz ... try 0
capture_data Warning: It is not RTLSDR_TUNER_E4000
set fc_programmed=fc_requested
Allocating 15 zero-copy buffers

input level: avg abs(real) 0.474532 avg abs(imag) 0.475071
Hit        PAR [10.8244 10.0183]dB
PSS XCORR  cost 4.52283s
Hit  num peaks 9
try peak 0 tdd_flag 0
try peak 0 tdd_flag 1
try peak 1 tdd_flag 0
try peak 1 tdd_flag 1
try peak 2 tdd_flag 0
try peak 2 tdd_flag 1
try peak 3 tdd_flag 0
try peak 3 tdd_flag 1
try peak 4 tdd_flag 0
try peak 4 tdd_flag 1
try peak 5 tdd_flag 0
try peak 5 tdd_flag 1
try peak 6 tdd_flag 0
try peak 6 tdd_flag 1
try peak 7 tdd_flag 0
try peak 7 tdd_flag 1
try peak 8 tdd_flag 0
try peak 8 tdd_flag 1
No LTE cells were found...

**Comment by JiaoXianjun** [comment]
can you tell me how do you know 875MHz should have a cell?
I suggest you use a LTE phone to confirm.
