### ISSUE TITLE
256QAM is possible?

### ISSUE THREAD

**Issue by T-Yoshioka55** [JiaoXianjun/LTE-Cell-Scanner#42]
Is it possible to support 256QAM?

**Comment by JiaoXianjun** [comment]
It is possible if you develop the matlab script further.

**Comment by T-Yoshioka55** [comment]
Thank you for your reply.  Do you have any plans to develop SCRIPT?
 [ decode_pdsch.m ] script has a part of QAM settings . Looks possible if you add Map settings. 
I hope .

**Comment by JiaoXianjun** [comment]
currently no plan

**Comment by JiaoXianjun** [comment]
Can you share some IQ sample file to me that includes 256qam? Then I can take a look.

**Comment by T-Yoshioka55** [comment]
My data is mobile wimax and Now I try to demodulate by my self . 
thanks .
