### ISSUE TITLE
LTE-Cell-Scanner not showing any output

### ISSUE THREAD

**Issue by harshjoshi01** [JiaoXianjun/LTE-Cell-Scanner#57]
hello everyone, from last few days i am trying to scan LTE band using bladeRF and i found one library named "LTE-Cell-Scanner", but it is showing following error:

pi@raspberrypi:~/LTE-Cell-Scanner/build/src $ CellSearch --freq-start 1890000000
LTE CellSearch (release) beginning. 1.0 to 1.1.0: An enhanced LTE Cell Scanner/tracker. Xianjun Jiao ([putaoshu@msn.com](mailto:putaoshu@msn.com))
PPM: 0
correction: 1
init_board: 1 bladeRF devices found! The 1st one will be used:
Backend: libusb
Serial: 7c6369174453442e9e177f41176685e3
USB Bus: 2
USB Address: 2
[INFO @ host/libraries/libbladeRF/src/helpers/version.c:79] Firmware version (v2.4.0) is newer than entries in libbladeRF's compatibility table. Please update libbladeRF if problems arise.
[INFO @ host/libraries/libbladeRF/src/helpers/version.c:103] FPGA version (v0.14.0) is newer than entries in libbladeRF's compatibility table. Please update libbladeRF if problems arise.
config_bladerf bladerf_get_lna_gain: Failed to get lna gain: Operation not supported
BLADERF device not FOUND!

how can i resolve this error?

**Comment by OliverB21** [comment]
Sounds stupid but have you updated "libbladeRF" (sudo apt upgrade libbladerf2)? If you can't might be worth rolling back the firmware on the BladeRF to the version the software is running on
